# Generated by Django 5.0.6 on 2025-10-17 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('license_plate', models.CharField(max_length=10)),
                ('vtype', models.CharField(default='AUTO', max_length=5)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('front', models.ImageField(upload_to='inspections/')),
                ('back', models.ImageField(upload_to='inspections/')),
                ('left', models.ImageField(upload_to='inspections/')),
                ('right', models.ImageField(upload_to='inspections/')),
                ('state', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('REJ', 'Rechazada')], default='PEN', max_length=3)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
