# Generated by Django 5.0.6 on 2025-10-17 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10)),
                ('vtype', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('COM', 'Comercial/Liviano')], max_length=4)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('use', models.CharField(default='Particular', max_length=30)),
                ('fuel', models.CharField(blank=True, max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'license_plate')},
            },
        ),
    ]
