# Generated by Django 5.0.6 on 2025-11-30 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_add_optional_color_and_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=10, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='use',
            field=models.CharField(default='Particular', max_length=30, verbose_name='Uso'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vtype',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('COM', 'Comercial/Liviano')], max_length=4, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
    ]
