# Generated by Django 5.0.6 on 2026-01-03 20:13

import django.db.models.functions.text
from collections import defaultdict

from django.conf import settings
from django.db import migrations, models


def normalize_plate(value):
    if not value:
        return ""
    return value.strip().upper()


def fix_vehicle_plate_duplicates(apps, schema_editor):
    Vehicle = apps.get_model("vehicles", "Vehicle")
    max_len = Vehicle._meta.get_field("license_plate").max_length
    seen = defaultdict(int)
    for vehicle in Vehicle.objects.all().order_by("owner_id", "license_plate", "pk"):
        key = (vehicle.owner_id, normalize_plate(vehicle.license_plate))
        if not key[1]:
            continue
        seen[key] += 1
        if seen[key] == 1:
            continue
        suffix = f"DUP{seen[key]-1}"
        prefix_len = max_len - len(suffix)
        prefix = key[1][:prefix_len] if prefix_len > 0 else ""
        new_plate = f"{prefix}{suffix}"
        Vehicle.objects.filter(pk=vehicle.pk).update(license_plate=new_plate)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_brand_alter_vehicle_fuel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Patente'),
        ),
        migrations.RunPython(fix_vehicle_plate_duplicates, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("license_plate"),
                models.F("owner"),
                name="uniq_vehicle_owner_plate_ci",
            ),
        ),
    ]
