# Generated by Django 5.0.6 on 2025-10-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('vehicle_type', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('COM', 'Comercial')], max_length=5)),
                ('plan_type', models.CharField(choices=[('RC', 'Responsabilidad Civil'), ('TC', 'Terceros Completo'), ('TR', 'Todo Riesgo')], max_length=2)),
                ('min_year', models.PositiveIntegerField(default=1995)),
                ('max_year', models.PositiveIntegerField(default=2100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('franchise', models.CharField(blank=True, max_length=80)),
                ('coverages', models.TextField(help_text='Lista de coberturas en markdown')),
                ('published_home', models.BooleanField(default=True)),
            ],
        ),
    ]
