# Generated by Django 5.0.6 on 2025-10-17 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REJ', 'Rechazado')], default='PEN', max_length=3)),
                ('mp_preference_id', models.CharField(blank=True, max_length=80)),
                ('mp_payment_id', models.CharField(blank=True, max_length=80)),
                ('receipt_pdf', models.FileField(blank=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policies.policy')),
            ],
        ),
    ]
