# Generated by Django 5.0.6 on 2025-12-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('policies', '0004_remove_policy_holder_remove_policy_license_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Falló')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Cargo pendiente',
                'verbose_name_plural': 'Cargos pendientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('concept', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('auth_code', models.CharField(blank=True, max_length=80)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payments.charge')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
