# Generated by Django 5.0.6 on 2026-01-01 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_charge_receipt"),
        ("policies", "0007_alter_policyinstallment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="installment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="policies.policyinstallment"),
        ),
    ]
