# Generated by Django 5.0.6 on 2026-01-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_delete_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='legacy_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy Charge amount (if available) for historic receipts. Used for post-mortem reporting only.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='legacy_charge_due_date',
            field=models.DateField(blank=True, help_text='Legacy Charge due date (if available) for historic receipts. Not part of the billing flow.', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='legacy_charge_id',
            field=models.IntegerField(blank=True, help_text='Legacy Charge PK preserved for audit after Charge removal. Charge no longer exists in runtime.', null=True),
        ),
    ]
