# Generated by Django 5.0.6 on 2026-01-02 18:37

import django.db.models.deletion
from django.db import migrations, models


def _backfill_payment_installments(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    PolicyInstallment = apps.get_model("policies", "PolicyInstallment")
    using = schema_editor.connection.alias

    for installment in PolicyInstallment.objects.using(using).exclude(payment_id__isnull=True):
        payment = Payment.objects.using(using).filter(id=installment.payment_id).first()
        if payment is None:
            raise RuntimeError(
                f"Cuota {installment.id} refiere a un pago {installment.payment_id} inexistente."
            )
        if payment.installment_id is None:
            Payment.objects.using(using).filter(id=payment.id).update(installment_id=installment.id)
        elif payment.installment_id != installment.id:
            raise RuntimeError(
                "Datos inconsistentes: el Pago %s ya está asociado a la cuota %s diferente de %s."
                % (payment.id, payment.installment_id, installment.id)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_receipt_legacy_charge_amount_and_more'),
        ('policies', '0007_alter_policyinstallment_id'),
    ]

    operations = [
        migrations.RunPython(
            _backfill_payment_installments,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='policies.policyinstallment'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('installment',), name='uniq_payment_installment'),
        ),
    ]
