# Generated by Django 5.0.6 on 2026-01-03 19:52

from django.db import migrations, models


def fix_payment_policies(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    PolicyInstallment = apps.get_model("policies", "PolicyInstallment")
    for payment in (
        Payment.objects.select_related("installment").filter(installment_id__isnull=False)
    ):
        try:
            installment = payment.installment
        except PolicyInstallment.DoesNotExist:
            continue
        if payment.policy_id != installment.policy_id:
            Payment.objects.filter(pk=payment.pk).update(policy_id=installment.policy_id)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_sync_payment_installment_fields'),
        ('policies', '0008_remove_policyinstallment_payment'),
    ]

    operations = [
        migrations.RunPython(fix_payment_policies, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('installment_id__isnull', True), ('policy_id__isnull', False), _connector='OR'), name='payment_installment_requires_policy'),
        ),
    ]
