# Generated by Django 5.0.6 on 2026-01-04 00:00

from django.db import migrations, models
from django.utils import timezone


def backfill_last_state_change(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.update(last_state_change_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_payment_payment_installment_requires_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="last_state_change_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="last_state_change_reason",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(backfill_last_state_change, reverse_code=migrations.RunPython.noop),
    ]
