# Generated by Django 5.0.6 on 2026-01-03 20:26

import re

import django.core.validators
from django.db import migrations, models


PERIOD_REGEX = re.compile(r"^(19|20)\d{2}(0[1-9]|1[0-2])$")


def period_from_installment(installment):
    start_date = getattr(installment, "period_start_date", None)
    if not start_date:
        return None
    return f"{start_date.year}{str(start_date.month).zfill(2)}"


def fix_invalid_periods(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    for payment in Payment.objects.select_related("installment").all():
        current_period = payment.period or ""
        if payment.installment_id:
            derived = period_from_installment(payment.installment)
            if derived and derived != current_period:
                Payment.objects.filter(pk=payment.pk).update(period=derived)
            continue
        if PERIOD_REGEX.match(current_period):
            continue
        replacement = payment.created_at.strftime("%Y%m") if payment.created_at else None
        if replacement:
            Payment.objects.filter(pk=payment.pk).update(period=replacement)


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_payment_state_trace"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_periods, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="payment",
            name="period",
            field=models.CharField(
                db_index=True,
                help_text="Período AAAAMM (mes entre 01 y 12).",
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El período debe tener el formato AAAAMM y representar un mes válido.",
                        regex="^(19|20)\\d{2}(0[1-9]|1[0-2])$",
                    )
                ],
            ),
        ),
    ]
