# Generated by Django 5.0.6 on 2026-01-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_payment_period"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_installment_requires_policy",
        ),
    ]
