# Generated by Django 5.0.6 on 2025-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, default='+54 9 221 000 0000', max_length=50, verbose_name='WhatsApp'),
        ),
    ]
