# Generated by Django 5.0.6 on 2025-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_contactinfo_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_threshold_days', models.PositiveIntegerField(default=7)),
                ('client_expiration_offset_days', models.PositiveIntegerField(default=2)),
                ('default_term_months', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajustes de la app',
                'verbose_name_plural': 'Ajustes de la app',
            },
        ),
    ]
