# Generated by Django 5.0.6 on 2025-11-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_add_timestamps'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='products.product'),
        ),
    ]
