# Generated by Django 5.0.6 on 2025-12-05 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policy_options_alter_policy_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='state',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='policy',
            name='claim_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('no_coverage', 'Sin cobertura'), ('expired', 'Vencida'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada'), ('inactive', 'Inactiva')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to=settings.AUTH_USER_MODEL, verbose_name='Titular'),
        ),
        migrations.CreateModel(
            name='PolicyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=10, verbose_name='Patente')),
                ('make', models.CharField(max_length=80, verbose_name='Marca')),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('version', models.CharField(blank=True, max_length=80, verbose_name='Versión')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('has_garage', models.BooleanField(default=False)),
                ('is_zero_km', models.BooleanField(default=False)),
                ('usage', models.CharField(default='privado', max_length=30)),
                ('has_gnc', models.BooleanField(default=False)),
                ('gnc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Vehículo de póliza',
                'verbose_name_plural': 'Vehículos de póliza',
            },
        ),
    ]
