# Generated by Django 5.0.6 on 2025-12-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_policyinstallment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinstallment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
