# Generated by Django 5.0.6 on 2026-01-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_policyinstallment_id'),
        ('payments', '0008_alter_payment_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyinstallment',
            name='payment',
        ),
    ]
