# Generated by Django 5.0.6 on 2026-01-04 02:30

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def normalize_plate(value):
    if not value:
        return ""
    return str(value).strip().upper()


def backfill_policy_vehicle(apps, schema_editor):
    Policy = apps.get_model("policies", "Policy")
    PolicyVehicle = apps.get_model("policies", "PolicyVehicle")
    Vehicle = apps.get_model("vehicles", "Vehicle")
    for policy in Policy.objects.filter(vehicle_id__isnull=True).select_related("user"):
        if not policy.user_id:
            continue
        try:
            policy_vehicle = PolicyVehicle.objects.get(policy_id=policy.id)
        except PolicyVehicle.DoesNotExist:
            continue
        plate_norm = normalize_plate(policy_vehicle.plate)
        if not plate_norm:
            continue
        vehicle = Vehicle.objects.filter(owner_id=policy.user_id, license_plate=plate_norm).first()
        if not vehicle:
            vehicle = Vehicle.objects.create(
                owner_id=policy.user_id,
                license_plate=plate_norm,
                vtype="AUTO",
                brand=policy_vehicle.make or "Desconocida",
                model=policy_vehicle.model or "Desconocido",
                year=policy_vehicle.year or timezone.now().year,
            )
        Policy.objects.filter(pk=policy.pk).update(vehicle_id=vehicle.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0008_remove_policyinstallment_payment"),
        ("vehicles", "0004_alter_vehicle_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="policyvehicle",
            name="policy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_vehicle",
                to="policies.policy",
            ),
        ),
        migrations.RunPython(backfill_policy_vehicle, reverse_code=migrations.RunPython.noop),
    ]
